import { describe, expect, it } from "vitest";
import { resolveInsightEmbeddingDreamReason } from "@/lib/insights/dream";

describe("insight embedding dream", () => {
  it("selects missing embeddings", () => {
    expect(
      resolveInsightEmbeddingDreamReason({
        contentHash: "hash-a",
        embeddingModel: "model-a",
        existingContentHash: null,
        existingEmbeddingModel: null,
      }),
    ).toBe("missing");
  });

  it("selects embeddings generated by an older model", () => {
    expect(
      resolveInsightEmbeddingDreamReason({
        contentHash: "hash-a",
        embeddingModel: "model-b",
        existingContentHash: "hash-a",
        existingEmbeddingModel: "model-a",
      }),
    ).toBe("model_changed");
  });

  it("selects embeddings whose source content changed", () => {
    expect(
      resolveInsightEmbeddingDreamReason({
        contentHash: "hash-b",
        embeddingModel: "model-a",
        existingContentHash: "hash-a",
        existingEmbeddingModel: "model-a",
      }),
    ).toBe("content_changed");
  });

  it("skips embeddings that are already current", () => {
    expect(
      resolveInsightEmbeddingDreamReason({
        contentHash: "hash-a",
        embeddingModel: "model-a",
        existingContentHash: "hash-a",
        existingEmbeddingModel: "model-a",
      }),
    ).toBeNull();
  });
});
