export const WEEKLY_REPORT_GENERATION_CREDIT_COST = 450;
export const WEEKLY_REPORT_REGENERATE_CREDIT_COST = 250;

export const PRESENTATION_JOB_CREDIT_COST = 1500;
export const PRESENTATION_RETRY_CREDIT_COST = 600;
